---
title: "Analysis 2"
author: "Luka Pandza"
date: "11/21/2021"
output: html_document
---

---
title: "Poker Analysis"
author: "Luka Pandza"
date: "10/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r utilities}
update = function(bb_stacks = c(0), filepath) {
  stacks = read.delim(filepath, header = FALSE, sep = "\n")
  v_stacks = stacks[, 1]
  big_blind = v_stacks[1]
  v_stacks = v_stacks[-1]
  start_amount = v_stacks[1]
  bb_stacks_loc = round(v_stacks / big_blind, 1)
  start = bb_stacks[length(bb_stacks)] - (start_amount / big_blind)
  bb_stacks_loc = bb_stacks_loc + start
  return(c(bb_stacks, bb_stacks_loc))
}
```

```{r process_data}
bb_stacks = c(0)

bb_stacks = update(bb_stacks, "record-Fri-Oct-22-23-29-54-2021.txt")

bb_stacks = update(bb_stacks, "record-Sat-Oct-23-19-27-20-2021.txt")
bb_stacks = update(bb_stacks, "record-Sat-Oct-23-21-21-33-2021.txt")
bb_stacks = update(bb_stacks, "record-Sat-Oct-23-23-29-23-2021.txt")

bb_stacks = update(bb_stacks, "record-Sun-Oct-24-00-07-41-2021.txt")
bb_stacks = update(bb_stacks, "record-Sun-Oct-24-19-52-10-2021.txt")

bb_stacks = update(bb_stacks, "record-Sun-Oct-31-23-01-21-2021.txt")

bb_stacks = update(bb_stacks, "record-Sun-Nov-14-12-50-06-2021.txt")

bb_stacks = update(bb_stacks, "record-Mon-Nov-15-21-40-22-2021.txt")
bb_stacks = update(bb_stacks, "record-Mon-Nov-15-22-36-01-2021.txt")

bb_stacks = update(bb_stacks, "record-Tue-Nov-16-14-30-52-2021.txt")
bb_stacks = update(bb_stacks, "record-Tue-Nov-16-20-58-53-2021.txt")

bb_stacks = update(bb_stacks, "record-Wed-Nov-17-11-56-23-2021.txt")
bb_stacks = update(bb_stacks, "record-Wed-Nov-17-18-54-39-2021.txt")
bb_stacks = update(bb_stacks, "record-Wed-Nov-17-19-55-55-2021.txt")
bb_stacks = update(bb_stacks, "record-Wed-Nov-17-21-04-26-2021.txt")

bb_stacks = update(bb_stacks, "record-Thu-Nov-18-09-16-23-2021.txt")

bb_stacks = update(bb_stacks, "record-Fri-Nov-19-12-06-44-2021.txt")
bb_stacks = update(bb_stacks, "record-Fri-Nov-19-19-28-07-2021.txt")
bb_stacks = update(bb_stacks, "record-Fri-Nov-19-21-18-59-2021.txt")

bb_stacks = update(bb_stacks, "record-Sat-Nov-20-14-21-00-2021.txt")
bb_stacks = update(bb_stacks, "record-Sat-Nov-20-15-37-40-2021.txt")

bb_stacks = update(bb_stacks, "record-Sun-Nov-21-12-42-54-2021.txt")
bb_stacks = update(bb_stacks, "record-Sun-Nov-21-14-52-38-2021.txt")
bb_stacks = update(bb_stacks, "record-Sun-Nov-21-16-42-39-2021.txt")

bb_stacks = update(bb_stacks, "record-Mon-Nov-22-14-47-29-2021.txt")
bb_stacks = update(bb_stacks, "record-Mon-Nov-22-16-08-08-2021.txt")

bb_stacks = update(bb_stacks, "record-Tue-Nov-23-21-57-16-2021.txt")

bb_stacks = update(bb_stacks, "record-Wed-Nov-24-17-55-27-2021.txt")
bb_stacks = update(bb_stacks, "record-Wed-Nov-24-20-31-34-2021.txt")
```

### Graphing progress
```{r bb100k}

num_hands = length(bb_stacks)

## avg bb/100:
num_100_samples = floor(num_hands / 100)
bb_100s = sapply(2 : length(bb_stacks), 
                        function (x) (bb_stacks[x] - bb_stacks[x - 1]))

# histogram:
hist_width = 5

lo = (min(bb_100s) - min(bb_100s) %% hist_width) - hist_width
hi = (max(bb_100s) + (hist_width - max(bb_100s) %% hist_width)) + hist_width

breaks = seq(from = lo, 
             to = hi, 
             by = hist_width)

hist(bb_100s,
     xlim = c(lo, hi),
     breaks = breaks, 
     col = 'white')

avg_bb_100 = mean(bb_100s) * 100
var_bb_100 = var(bb_100s)
sd_bb_100 = sqrt(var_bb_100) * 100

## probability that I am profitable:
p_profit = 1 - pnorm(0, avg_bb_100, sd_bb_100)

## visualize hands:
plot(1:length(bb_stacks), 
     bb_stacks, 
     type = 'l', 
     lty = 1, 
     xlab = "Hand #", 
     ylab = "Cumulative Stack Size [# of big blinds]", 
     lwd = 1, 
     pch = NULL)

lines(c(1, length(bb_stacks)), c(bb_stacks[1], bb_stacks[length(bb_stacks)]), 
      col = "lightgreen", 
      lty = 2)

lines(c(0, length(bb_stacks)), c(0, 0), 
      col = "red", 
      lty = 2)

legend(0, max(bb_stacks), 
       c(paste('# of Hands = ', as.character(num_hands)), 
         paste('MEAN bb/100 = ', as.character(round(avg_bb_100, 2))), 
         paste('VAR bb/100 = ', as.character(round(var_bb_100, 2))), 
         paste('SD bb/100 = ', as.character(round(sd_bb_100, 2))), 
         paste('P(profit) = ', as.character(round(p_profit, 2)))),
       lty=c(2, 2, 2), 
       col=c('white', 'white', 'white'))
```